name: tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: tests

    strategy:
      matrix:
        include:
          - php: '8.1'
          - php: '8.2'
          - php: '8.3'
          - php: '8.4'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
        with:
          php-version: "${{ matrix.php }}"
          coverage: none
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: composer tools:run:phpunit
